### ISSUE TITLE
Constraint on use_repr flag

### ISSUE THREAD

**Issue by Kostya-228** [cloudblue/django-rql#12]
Hi!
I started using django-rql and interested in this constraint: "`use_repr` can be used neither with `ordering` nor `search`" for choices fields. 
And have a question: Why?)

**Comment by Kostya-228** [comment]
Link for documentation on this constraint: https://django-rql.readthedocs.io/en/latest/user_guide.html#use-repr

**Comment by maxipavlovic** [comment]
Hi, @Kostya-228 thx for a question.

There are several reasons for such constraint:
1. Representation and real values may be of different types: for example, DB value can easily be integer. In such case there may be ambiguity for ordering operations. For example:
`field = Choices((0, 'xyz'), (1, 'abc'))`
In such case, we will get reversed results for `ordering(field)`.

2. Non-exact string type search/like/ilike lookup operators are impossible to interpret (exact _eq_ comparison is supported out of the box). For example:
`field = Choices(('db', 'repr'))`
If we would allow a query `like(field,*ep*)` we would need to have a way to map all the possible values to db value equivalents, which can't be solved by library itself.

Hope that makes sense, but I should mention that you are free to use _custom_ filters to support any type of behavior, you want: https://django-rql.readthedocs.io/en/latest/user_guide.html#custom

**Comment by Kostya-228** [comment]
Thank you very much for such a detailed answer. Now I understand the reasons. I think we can close the issue.
