### ISSUE TITLE
No RQLFilterClass constraints question

### ISSUE THREAD

**Issue by 1jeanpaul1** [cloudblue/django-rql#16]
Hello,

was wondering if its possible to allow every field in a model to be filter-able without explicitly writing it out? Didn't see that being an option in the documentation so I assume the answer is no, but figured I would ask anyways.

Basically enable the user to filter in whichever way they want without writing out an RQLFilterClass

**Comment by maxipavlovic** [comment]
Hi, Jean Paul.

I have to admit that you are right. Currently it's not possible, but it sounds like a good proposal, in general.
I forsee several corner cases, but I have added to my backlog to think thoroughly on that.  Thank you.

P.S. At this point, I don't think that it's a good way to get totally rid of RQLFilterClass even in such scenario as "explicit is better than implicit". Will see :)

**Comment by maxipavlovic** [comment]
@1jeanpaul1 you can check [the latest RQL version >=3.10.0](https://pypi.org/project/django-rql/) to check if that fits you
