### ISSUE TITLE
Custom filter type check

### ISSUE THREAD

**Issue by net-free** [cloudblue/django-rql#21]
**Problem**
For custom filters we should manually validate input value type (data.str_value).

**Example**
```python
# Model
class ExampleModel(Model):
    external_id = IntegerField()


# Filter
class ExampleFilterClass(RQLFilterClass):
    MODEL = ExampleModel

    FILTERS = [
        {
            'filter': 'external_id',
            'custom': True,
            ...
        },
    ]

    def build_q_for_custom_filter(self, data):
        if data.filter_name == 'external_id':
            return Q(**{f'external_model__id__{data.django_lookup}': data.str_value})
```
Url: /example?external_id=test | GET
Http code: 500
Response body: invalid literal for int() with base 10: 'test'

Expected
Http code: 400
Response body: {'error_code': 'VAL_001', 'errors': ['Bad filter query: filter - external_id, operation - eq, value - test']}

**Proposed solution**
Allow to specify ORM field type for custom fields. 
We could do it the same as for dynamic.

```python
    FILTERS = [
        {
            'filter': 'external_id',
            'custom': True,
            'field': IntegerField(),
            ...
        },
    ]
```

**Comment by maxipavlovic** [comment]
Makes total sense. Let's go this way.
